---
title: "Final Project"
author: "Olly Gill"
date: "12/10/2019"
output: html_document
---

```{r setup, setting up the libraries and data sets, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Loading the libraries for the project.

library(gt)
library(janitor)
library(broom)
library(highcharter)
library(tidyverse)

# Loading the data sets for the project.

athlete_events <- read_csv("athlete_events.csv")
winter_medals <- read_csv("winter.csv")
summer_medals <- read_csv("summer.csv")
noc_regions <- read_csv("noc_regions.csv")
```

Medals:
```{r, creating a graph of medals won by the top scoring counties}

# I created a graph of the medals won by the top scoring countries and divided
# the medals by what kind of medal they are also. I did this for the summer games
# and then in my shiny app I copy and pasted the code again to make the same thing
# for the winter season but used the winter data set instead.

# First I took the summer medals data set and selected the variables that I needed to 
# make the data set. I chose country medal and year. 
# I then grouped by country to get the medals won per country. I also grouped by medal
# because I wanted to also know how many of each kind of medal the country won.
# I then counted by country to know how many each country got.
# I then arranged by desc so that I could select the top medaling countries. I used head
# to take the top countries and selected 30 so that I got around 10-15ish countries.
# I then used ggplot to plot the graph with the right axes and used group and fill for 
# medal so that the different medals were different colors.
# I used geom_col to make columns for the data.
# I added labels and a theme command to make the title large and bolded.

summer_medals %>%
  select(Country, Medal, Year) %>%
  group_by(Country, Medal) %>%
  count(Country) %>%
  arrange(desc(n)) %>%
  head(30) %>%
  ggplot(aes(x = Country, y = n, group = Medal, fill = Medal)) +
  geom_col() +
  labs(title = "The Top Medaling Countries: Sumer Olympic Games",
       subtitle = "Which Countries Over Time Have Succeeded The Most?", 
       x = "Country", 
       y = "Number of Medals") +
  theme(plot.title = element_text(size = 16, face = "bold"))
```

Gender Trends:
```{r, creating a graph of gender trends by season}

# I created a graph of the trends of the number of male and female athletes that
# were participating in the summer games. I did this for the summer games and then
# in my shiny app I copy and pasted the code again to make the same thing
# for the winter season but used filter == winter instead.

# I grouped by year and sex to see how the trends in male vs female participation
# changed over the years of the Olympics.
# I then counted to get the total number of each gender in each year.
# I then arranged by year to get the most recent numbers at the bottom and the first
# games at the top of the list.

Gender_Per_Year <- athlete_events %>%
  filter(Season == "Summer") %>%
  group_by(Year, Sex) %>%
  count() %>%
  arrange(Year)

# I took the data I modified above and pipped it into ggplot with year on the x axis
# and the number of athletes on the y axis. I grouped by sex and made them different
# colors to make the data pop.
# I added geom point and geom line to make it a line graph.
# Labs added in labels and a title and subtitle.
# I added a theme command to make the title large and bolded.
      
Gender_Per_Year %>%
  ggplot(aes(x = Year, y = n, group = Sex, color = Sex)) +
  geom_point() +
  geom_line() +
  labs(title = "Male & Female Summer Olympic Athletes Over Time", 
       subtitle = "How has the number of male and female athletes changed over the years?", 
       x = "Year", 
       y = "Number of Athletes") +
  theme(plot.title = element_text(size = 16,face = "bold"))
```

Overall Trends: Athletes, Events, Nations
```{r, making a series of overall trend graphs}

# I wanted to make a series of three overall trend graphs: athletes, events, nations.
# I took this graph for athletes and used it as a template for the next two. Only for 
# the events and nations I just adjusted the summarize command so instead of 
# athletes = length(unique(ID)) it would be for events = or nations = . I then adjusted
# the axes to make this graph for events and nations as well just by changing the y axis 
# variable. I made the new graphs in shiny.

# First I took the big data set and filtered for sport so that I was only looking at the 
# main sport events and wasn't looking at the art competitions.
# I grouped by year and season to get the number of athletes per year per season to look
# at the trends that differed by winter or summer.
# I then summarized to create an athletes variable that only took each name, or ID, once 
# because several of the athletes are listed many times due to being in many events. That 
# is why I used the length(unique(ID)) command so each name only came up once.

athlete_data <- athlete_events %>% 
  filter(Sport != "Art Competitions") %>%
  group_by(Year, Season) %>%
  summarize(Athletes = length(unique(ID)))

# I then used ggplot to create a plot with the year on the x axis and the number of athletes 
# on the y axis. I grouped by and colored season to get two separate plots one for each season
# and I colored them to make them stick out.
# I added geom point and line to make a line graph of the data.
# I added scale color manual because I wanted to be able to select the colors of the lines on the
# graph. I added labs to add in labels and axis titles.
# I added a theme command to make the title large and bolded.

athlete_data %>%       
  ggplot(aes(x = Year, y = Athletes, group = Season, color = Season)) +
  geom_point() +
  geom_line() +
  scale_color_manual(values = c("pink","navy")) +
  labs(title = "The Number of Athletes Over Time", 
       x = "Year",
       y = "Athletes",
       subtitle = "Have females or males been more involved?") +
  theme(plot.title = element_text(size = 16,face = "bold"))
```

Maps of Origin:
```{r, making the maps of where athletes came from}

# Here I made one basic template for a map and then in my shiny app I adjusted the template
# to make maps for several different games and the years they were hosted. All I had to
# do to do that is change every country name/date in the following code. For example, for the
# sochi map every time paris appears in the template I switched it to sochi and for the title
# and filter command I changed the year as well.

# First I took the athletes data set and joined it with another region data set that I got off
# the internet. I then used filter to get rid of all the na values in the regions column of the 
# data set. I stored this all as regions.

regions <- athlete_events %>% 
  left_join(noc_regions, by = "NOC") %>%
  filter(!is.na(region))

# I then took the region data and filtered for the paris games which were in 1900 and they were
# the summer games. I then grouped by region to get the region that everyone came from as different
# groups. I then created a Paris variable that took every athlete and only selected their name
# once so I wouldn't double count someone coming from one place.
      
Paris_data <- regions %>% 
  filter(Games == "1900 Summer") %>%
  group_by(region) %>%
  summarize(Paris = length(unique(ID)))

# I then used the map_data command to turn data from the maps package in to a data frame suitable 
# for plotting with ggplot2. I set the region to world because I wanted to plot the data everywhere
# in the world. I saved this data.

world <- map_data("world")
   
# I then created a new data set where region was only listed once. I did this again by using the 
# unique command so the same regions weren't grouped multiple times.

map_data <- tibble(region = unique(world$region))

# I then took the new map data and joined it together with my Paris data by region.      

map_data <- map_data %>% 
  left_join(Paris_data, by = "region")

# I then took the Paris value in the map_data and got rid of the na values and made them 0s.
  
map_data$Paris[is.na(map_data$Paris)] <- 0
      
# I then joined together the updated map data datset and the world data by region.

world <- left_join(world, map_data, by = "region")
      
# Once I had all the data I created a plot of the data with the long and lat values
# as the axis variables so that I would be making a map. 
# I grouped by group so every group of people from a region would be together.
# I added geom_polygon to create a map and used fill to add in the Paris data.
# I used guides and scale fill gradient to make a gradient legend that showed the 
# white regions of the graph to be where few athletes were from and a bright orange
# where the athletes are concentrated. The legend shows this.
# I used labs to add a title.
# I used theme to get rid of the axis ticks and text. I made the background navy like
# a normal map would be. I made the title in the center of the top.

ggplot(world, aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = Paris)) +
  guides(fill = guide_colourbar(title = "Athletes")) +
  scale_fill_gradient2(low = "white", high = "orange") +
  labs(title = "Paris 1900",
       x = NULL,
       y = NULL) +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_rect(fill = "navy"),
        plot.title = element_text(hjust = 0.5))
```

Body Characteristics:
```{r, making height and weight trend graphs}

# I made the code for one graph and then when I went to make the weight graph I 
# just switched the y axis variable to weight instead of the current height one in shiny.

# I took the big athlete data set and took out the na values and pipped it into a 
# ggplot that made Year a factor variable and plotted the height values on the y axis.
# I then filled by sex so that there would be two separate trends that showed the difference
# in the two genders.
# I added geom_boxplot to make a boxplot of the data.
# I then used scale fill manual so that I could pick the colors of the different graph values.
# I then had to adjust the size and angle of the year values so that they would be small enough
# to all fit on the axis without overlapping.
# I added in labs to make a nice title, subtitle, and axes labels.
# I used theme to make the title bolded and large.

athlete_events %>% 
  na.omit() %>%
  ggplot(aes(x = as.factor(Year), y = Height, fill = Sex)) +
  geom_boxplot() +
  scale_fill_manual(values = c("pink","blue")) +
  theme(axis.text.x = element_text(size = 5, angle = 20)) +
  labs(title = "Height Trends In Athletes Over Time", 
             x = "Olympic Year", 
             y = "Height (cm)",
             subtitle = "How have Olympic athletes' heights fluctuated over time?") +
  theme(plot.title = element_text(size = 16,face = "bold"))
```

Age:
```{r, making an age histogram}

# I took the big data set and took out all of the na values.
# I pipped it into ggplot to make a plot with age on the x axis.
# I added in geom_histogram to make a histogram with the height representing the number
# of athletes in each height bin. I added some cool colors in the graph as well.
# I facted by sex to get two separate graphs by gender.
# I added in labs to make a nice title and axes labels.
# I added theme to get rid of the legend, and to make the title large and bold.

athlete_events %>%
  na.omit() %>%
  ggplot(aes(x = Age)) +
  geom_histogram(binwidth = 1, aes(fill = ..count..), color = "pink", fill = "black") +
  facet_wrap(~Sex) +
  labs(title = "Age Distribution of Olympics Athletes",
       subtitle = "Data Taken From the Olympics 1896-2016",
       x = "Age",
       y = "Number of Athletes") +
  theme(legend.position = "none",
        plot.title = element_text(size = 16,face = "bold"))
```

Boxplot Age & Medals:
```{r, boxplot of the ages people are based on what medals they won}

# I made a model of the code for this boxplot for one season and then in shiny I changed 
# the filter command to made one for the summer season as well.

# I tok the data and got rid of the na values in the Age data column and filtered for 
# the winter season.

age_data <- athlete_events %>%
  na.omit(Age) %>%
  filter(Season == "Winter")

# I then took the data and made a series of ifelse statements and stored them all as the
# Medal data in the age_data dataset.
# First I took the values of medal for which the athletes did not win a medal and I said for
# those values to come up as 'others'.
# I then took the values for which gold came up to store then as gold. I did the same for silver.
# Then for the remaining values I said for them to come up as bronze.
    
age_data$Medal <- ifelse(is.na(age_data$Medal),"others",
                         ifelse(age_data$Medal== "Gold","Gold",
                                ifelse(age_data$Medal== "Silver","Silver","Bronze")))

# I then took this new data and made a boxplot with the highcharter plackage which would 
# allow for me to have a reactive cursor over the boxplot boxes.
# I put age on the y axis and then did this packages version of faceting my gender and 
# the type of medal as well.
# I made the type = column because every example of this type of chart I googled had type set
# to column.
# I then added in some details with a title and substitle.
    
hcboxplot(x = age_data$Age, var = age_data$Sex, var2 = age_data$Medal, outliers = FALSE) %>% 
  hc_chart(type = "column") %>%
  hc_title(text = "Age Distributed: Medal Winners & Others") %>%
  hc_subtitle(text = "Data collected From the Winter Olympics 1896-2016")
```

Density Age:
```{r, making a density plot of age}

# First I made an overall density plot of age. Then for my second one in which I wanted there
# to be two separate density plots by gender I added in a line of code that said fill = sex 
# insise the aesthetics command on ggplot.

# I took the big athlete data set and pipped it into ggplot with age on the x axis.
# I then added geom_density and made the inside of graph pink with a black border.
# I added labs to put a title and axes labels on the graph.
# I added theme_minimal to make the background white.

athlete_events %>%
  ggplot(aes(x = Age)) +
  geom_density(color = "black", fill = "pink") +
  labs(title = "Age Distribution",
       x = "Age", 
       y = "Density",
       subtitle = "What is the overall density of the different athlete ages?") +
  theme(plot.title = element_text(size = 16,face = "bold")) +
  theme_minimal()
```

Age and Medals:
```{r, line graph of what age medal vs non medal winners are}

# I made a model of the code for this line graph for one season and then in shiny I changed 
# the filter command to made one for the summer season as well.

# I took the big athlete data set and I grouped by year season and medal because I wanted to 
# find the average age of medal winners and the non medal winners every year the games were hosted
# for that specific season. I then filtered for the season.
# I used summarise to make a value mean that finds the average of the age of the groups of people.

wintermedals <- athlete_events %>% 
  group_by(Year, Season, Medal) %>% 
  filter(Season == "Winter") %>%
  summarise(mean = mean(Age, na.rm = TRUE))

# I took this data and piped it into the ggplot function with year on the x axis and then the average
# age values on the y axis. I grouped by and colored medal so that each type of medal had its own
# groupings color coated.
# I added in geom_point and geom_line to make a line graph of the data so that it was easy to visualize.
# I used labs to add in a title and axes labels and subtitle.
# I then made the title big and bolded.

wintermedals %>% 
  ggplot(aes(x = Year, y = mean, group = Medal, color = Medal)) +
  geom_point() +
  geom_line()  +
  labs(title = "Age of Athletes Winning Medals",
       subtitle = "What are the typical ages of medaling athletes?",
       x = "Year",
       y = "Average Age") + 
  theme(plot.title = element_text(size = 16,face = "bold"))
```

Female vs. Male Over Time:
```{r, making a linear model of the number of males vs females over time}

# I took the big athlete data set and filtered for the specific years I wanted. I chose a
# random group of years that were sort of spread over to cover the trend of time. 
# I grouped by the year, sex, and region they were from.
# I then made a variable that accounetd for each athlete once. I didn't want to double count
# anyone cause that would ruin the point of the graph so that is why I used length(unique(ID)).
# I then spread the two key variables across the columns of data.

nation_numbers <- athlete_events %>% 
  filter(Year %in% c(1900,1936,1976,1984,2016)) %>%
  group_by(Year, NOC, Sex) %>%
  summarize(number = length(unique(ID))) %>%
  spread(Sex, number)

# I then used the names replacement function to change values in the naiton_numbers data set.
# I then used [3:4] in order to change the 3rd element to Male and the 4th element to Female.
# I then got rid of the na values for Male and then Female in the nation_numbers data set and 
# replaced them with 0s.

names(nation_numbers)[3:4] <- c("Male","Female")
nation_numbers$Male[is.na(nation_numbers$Male)] <- 0
nation_numbers$Female[is.na(nation_numbers$Female)] <- 0
nation_numbers$Year <- as.factor(nation_numbers$Year)

# I then took the data and pipped it into a ggplot function with male of the y axis and female
# on the x axis. For some reason when I put them in the correct x and y pairings the data was
# showing up backwards so I had to manually put them in the opposite labels in the labs command.
# I grouped by year to get the number of the gender every year and made them different colors to pop.
# I then added in geom_point and an abline to make a line trend through the graph.
# I added in geom_smooth to make a linear model of the trend of points every year.
# I added in labs to give the graph axes labels and a title and subtitle.

nation_numbers %>%
  ggplot(aes(x = Male, y = Female, group = Year, color = Year)) +
  geom_point(alpha = 0.5) +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed") +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Female vs. Male Olympians from participating NOCs",
       x = "Number of Female Participants",
       y = "Number of Male Participants",
       subtitle = "How are the number of males vs. females different?")
```

Regression:
```{r, making a regression model}

# I took the big athlete data set and took out all of the na values.
# I then selected the variables that I wanted to use in my model.
# I used mutate to make gold a logical variable that would be TRUE if the medal was gold and
# FALSE if it wasn't.

athlete_clean <- athlete_events %>%
  na.omit() %>%
  select(Age, Medal, Sex) %>%
  mutate(gold = as.logical(ifelse(Medal == "Gold", "TRUE", "FALSE")))

# I then made the model with the clean data set and made a formula of age describing the gold.
    
model <- lm(data = athlete_clean, formula = gold ~ Age)

# I then took my mdodel and in the tidy command I made a 90% credible interval for the model.
# I selected the variables of the tidy model that I wanted to use in my table. I then made row
# names that were labels of the data in the columns.

model_data <- tidy(model, conf.int = TRUE, conf.level = 0.90) %>%
  select(term, estimate, conf.low, conf.high) %>%
  mutate(term = c("Intercept", "Age")) 

# I then took the data above and piped it into a gt function.
# I added a title and subtitle.
# I labeled all of the columns to what I wanted each of them to be.
# I then aligned all of the values/words of that they were in the center of their cells.
# I used fmt_number in order to adjust the number of decimal places that I wanted.

table <- model_data %>%
  gt() %>%
  tab_header(title = "The Affect of Age On Winning A Gold Medal", 
             subtitle = "Will being older make you less likely to win the gold?") %>% 
  cols_label(
    "estimate" = "Coefficient",
    "conf.low" = "5th percentile",
    "conf.high" = "95th percentile",
    "term" = " ") %>%
  cols_align("center") %>%
  fmt_number(
    columns = c("estimate", "conf.low", "conf.high"),
    decimals = 5,
    use_seps = FALSE
  )

# I saved the table as an html so that I could output the whole table in my shiny app.

table %>%
  gtsave("table.html")
```

Top 10 Athletes:
```{r, top 10 athletes chart}

# I took the athlete data set and filtered for the summer season in the year that I wanted. 
# I also got rid of the na values in the medal column.
# I grouped by name to get each individual athlete with their own set of data.
# I then used summarise to count the number of medals that each athlete won.
# I arranged by desc so that I could select the top 10 athletes using head.

athlete <- athlete_events %>%
  filter(!is.na(Medal), Season =='Summer', Year == 2016) %>%
  group_by(Name) %>%
  summarize(medal = n()) %>% 
  arrange(desc(medal)) %>% 
  head(n = 10)

# I then took the highchart function and made the height of the graph 800px.
# I then used the labels command to put in the two variables I was plotting: name and medals.
# I specified the colors I wanted the graph to use going from red with the top number of medals
# to light yellow for the lowest. I also specified to make a pie chart and then 
# adjusted the center values to make the graph a certain size and place (I experimented with
# these values until I liked the numbers I chose.)

highchart(height = "800px") %>% 
  hc_add_series_labels_values(athlete$Name, athlete$medal, 
                              colors = substr(heat.colors(10), 0, 7),
                              type = "pie", colorByPoint = TRUE, center = c('46%', '40%')) 
```

Top 10 Teams:
```{r, top 10 sports chart}

# I took the athlete data set and filtered for the summer season in the year that I wanted. 
# I also got rid of the na values in the medal column.
# I grouped by sport to get each individual sport with their own set of data.
# I then used summarise to count the number of medals that each sport won.
# I arranged by desc so that I could select the top 10 sports using head.

Sport <- athlete_events %>%
  filter(!is.na(Medal), Season=='Summer', Year == 2016) %>%
  group_by(Sport) %>%
  summarize(medal=n()) %>%
  arrange(desc(medal)) %>%
  head(n=10)

# I then took the highchart function and made the height of the graph 800px.
# I then used the labels command to put in the two variables I was plotting: sport and medals.
# I specified the colors I wanted the graph to use going from red with the top number of medals
# to light yellow for the lowest. I also specified to make a pie chart and then 
# adjusted the center values to make the graph a certain size and place (I experimented with
# these values until I liked the numbers I chose.)

highchart(height = "700px") %>% 
  hc_add_series_labels_values(Sport$Sport, Sport$medal, 
                              colors = substr(heat.colors(10), 0 , 7),
                              type = "pie", colorByPoint = TRUE, center = c('46%', '40%'))
```

